version: '3.8'

services:
  karaoke-app:
    container_name: karaoke_platform_container
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    ports:
      - "5000:8080" # Приложение доступно по адресу http://localhost:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      # Сохраняем базу данных SQLite
      - ./instance:/app/instance
      # Сохраняем загруженные файлы пользователей и готовые MP4
      - ./wwwroot/uploads:/app/wwwroot/uploads
      - ./wwwroot/output:/app/wwwroot/output
      # Сохраняем скачанные ИИ-модели разделения вокала
      - ./Models:/app/Models
      - /root/.cache/audio-separator:/root/.cache/audio-separator
    restart: always